### ISSUE TITLE
Functions for manipulating the shape of file views/tables

### ISSUE THREAD

**Issue by philerooski** [Sage-Bionetworks/annotator#12]
We are missing some simple functions for manipulating file views:

* remove columns from a file view
* remove rows from a file view

These lie in the gray area between useful for annotations and general Synapse functionality, but I think they would be a good fit for `utils` -- and can be referenced from `Pipeline`.

@teslajoy Add whatever else you can come up with. Thanks.

**Comment by teslajoy** [comment]
Enable updating scope of an entity-view `project or file type`. 
This would handle row manipulation to a certain extend. (ex. adding or removing scopes from project view would add and remove remove rows respectively)

**Comment by philerooski** [comment]
Good idea. Can you create a separate issue for that?

**Comment by philerooski** [comment]
I don't think it's possible, and probably not desirable, to be able to delete a row from a file view. Since the file view query grabs whatever files are under the scope each time it's loaded it would have to maintain an "ignore" list to prevent itself from including a dropped row in a query.

Technically you can delete the row by deleting the file, but that's not really what we're after. I think best solution is to drop the row from the dataframe, but not attempt to drop from synapse. But when dropping columns we need to sync with synapse, so we'll keep that functionality as originally envisioned.
