### ISSUE TITLE
Maintain lower case boolean capitalization in json2table

### ISSUE THREAD

**Issue by karawoo** [Sage-Bionetworks/annotator#91]
Our synapse annotations define booleans as lowercase `true`/`false`, but json2table converts them to upper case. I'll look into this, also cc-ing @kdaily on request in case there's a quick option that can tweak this behavior.

**Comment by kdaily** [comment]
Looks like this is where it happens:

https://github.com/Sage-Bionetworks/annotator/blob/master/annotator/schema.py#L83

I think it would have to be handled after this call to check if the column type was boolean and convert it to a string.

**Comment by karawoo** [comment]
This will not be needed if we address https://github.com/Sage-Bionetworks/synapseAnnotations/issues/535 by removing enumerated values

**Comment by karawoo** [comment]
closing since we've merged https://github.com/Sage-Bionetworks/synapseAnnotations/pull/538
